Added and updated frontend routing with comments
truongnguyenlinh/flixlist pull request #17
Opened 2021-08-11 15:45 UTC by nanonite9

Comments highlight changes to be made upon confirmation, including password functions and file names.

2021-08-12 01:24 UTC, Hunajpu approved these changes

2021-08-12 15:19 UTC, truongnguyenlinh commented on app/__init__.py
> +    # Employee??
Thanks for catching, it's been updated.

2021-08-12 20:28 UTC, truongnguyenlinh requested changes

2021-08-12 20:28 UTC, truongnguyenlinh commented on app/__init__.py
> +@app.route("/register", methods=("GET", "POST"))
Please add this route before `if __name__ == "__main__": app.run()`

2021-08-12 20:28 UTC, truongnguyenlinh commented on app/__init__.py
> +@app.route("/register", methods=("GET", "POST"))
@nanonite9

2021-08-13 17:57 UTC, truongnguyenlinh approved these changes
LGTM

2021-08-13 18:01 UTC, merged