Frontend of flix
truongnguyenlinh/flixlist pull request #9
Opened 2021-08-09 12:48 UTC by nanonite9

Frontend pages for friendflix, recsflix and footer. Additional changes to init and css.

2021-08-09 14:16 UTC, Hunajpu approved these changes
Excellent!

2021-08-09 20:34 UTC, truongnguyenlinh requested changes

2021-08-09 20:34 UTC, truongnguyenlinh commented on app/__init__.py
> +from flask import Flask, escape, request, render_template
This is a duplicate of line 3

2021-08-10 16:22 UTC, Hunajpu approved these changes

2021-08-10 20:15 UTC, truongnguyenlinh approved these changes
LGTM

2021-08-10 20:15 UTC, truongnguyenlinh commented on app/templates/recsflix.html
> +<!--
Update file name

2021-08-10 20:40 UTC, merged